#!/usr/bin/python

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sys

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

infileName = sys.argv[-1]
data = np.loadtxt(infileName, delimiter=',')

t = data[:,0]
charge = data[:,1]
x = data[:,2]
y = data[:,3]

nPads = 16*16
pitch = 0.4
for padx in [1.6 + ind*pitch for ind in range(16)]:
    for pady in [ind*pitch - 0.8 for ind in range(16)]:
        ax.scatter3D(padx, pady, 0, color = 'grey')

sc = ax.scatter3D(x, y, t, c = charge)
cb = plt.colorbar(sc, label=r'Raw Charge [C]')

ax.set_xlabel(r'x [cm]')
ax.set_ylabel(r'y [cm]')
ax.set_zlabel(r't [$\mu$s]')

plt.show()
