#!/usr/bin/python

from bulkPix import *

xmax = pad_pitch/2 + wall_thickness
ymax = pad_pitch/2 + wall_thickness

volumes = []

volumes.append(generate_central_pad(0))

volumes = volumes + generate_boundaries(xmax, ymax)

volumes.append(generate_argon(xmax, ymax))

top_level = {"name": "pixel pads",
             "periodicity": {"x": False,
                             "y": False,
                             "z": False},
             "bounds": {"xmin": xmin,
                        "xmax": xmax,
                        "ymin": ymin,
                        "ymax": ymax,
                        "zmin": zmin,
                        "zmax": zmax},
             "volumes": volumes}

enc = encoder.JSONEncoder(separators=(',', ': '),
                          indent = 4,
                          sort_keys = True)

print enc.encode(top_level)
